#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect the requirements:
# Install nginx
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School

apt-get -y install 
apt-get update
apt-get install -y nginx
echo "Hello World!" > /c/nginx-1.16.1/nginx-1.16.1/html
service nginx restart
