#!/usr/bin/env bash
# a Bash script that:
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when
# receiving a SIGQUIT or SIGTERM signal

pgrep holbertonscript.pid > /var/run/holbertonscript.pid
trap 'echo Y U no love me?!' 2
trap 'echo I hate the kill command; rm /var/run/holbertonscript.pid; exit' 15
trap 'rm /var/run/holbertonscript.pid; exit' 3
while true; do
    echo "To infinity and beyond"
    sleep 2
done

