#!/usr/bin/env bash
# This script prints "Best school" 10 times, and "hi" on the 9th iteration

COUNTER=0
while [ "$COUNTER" -lt 10 ]; do
	echo "Best School"
	if [ "$COUNTER" -eq 8 ]
	then
	    echo "Hi"
	fi
	let COUNTER=COUNTER+1
done
